services:
  ui:
    image: node:25-alpine
    restart: always
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app:rw
    working_dir: /app
    command: sh -c "npm i && npm run dev"

  app:
    image: golang:1.25-alpine
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/app:rw
      - ./docker/app_entrypoint.sh:/go/entrypoint.sh:ro
    entrypoint: [ 'sh', '/go/entrypoint.sh' ]
    secrets:
      - db_password
    environment:
      - DB_HOST=db
      - DB_HOST_TEST=db-test
      - DB_NAME=surf-share
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_PORT=5432
      - DB_USER=postgres
      - PORT=8080
      - UI_PORT=5173
    command: sh -c "cd /go/app && go run main.go"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080" ]
      interval: 2s
      timeout: 5s
      retries: 10

  db:
    image: postgres:18-alpine
    restart: always
    user: postgres
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql
      - ./db/scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=surf-share
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 10

  db-test:
    image: postgres:18-alpine
    restart: always
    user: postgres
    secrets:
      - db_password
    volumes:
      - db_test_data:/var/lib/postgresql
      - ./db/scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=surf-share
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password

volumes:
  db_data:
  db_test_data:

secrets:
  db_password:
    file: db/password